### ISSUE TITLE
Feature Request: Add label to the issue

### ISSUE THREAD

**Issue by TitouanVanBelle** [kentcdodds/issue-template#35]
I have created a template for reporting bug on a repository and I would like the issues generated through that template to be labelled (with the label 'bug' in this case).

**Comment by kentcdodds** [comment]
Great suggestion. Unfortunately this is not possible with the way the app works right now and would require a great deal of rearchitecting to make work (involving a proxy server which I don't think I have time to write).

Basically, currently when a user submits an issue, issue-template interacts with GitHub's api using the user's permissions. If the user can't add a label to an issue, neither can issue-template. To make this work, I'd have to write a server which would store your token to be able to add the label. I feel like this would be too much work for me. Feel free to do it yourself if you feel otherwise! :D

**Comment by Theoklitos** [comment]
Hello Kent, very useful project you have here :+1: 

Regarding this request, the doc https://developer.github.com/v3/issues/ says that when creating or editing an issue:
```
Only users with push access can set labels for new issues. 
Labels are silently dropped otherwise.
```
This is when passing the `labels` as a parameter. So if the user does not have permission, the desired labels are ignored - which is probably not a big deal. 

If the permissions are OK, just by adding this extra parameter it should work. Please correct me if I am wrong and thanks again.

**Comment by kentcdodds** [comment]
Ah, I see. So at least we'll get the benefit with those who have the right permissions. Better than nothing. I'll see when I can get to this... PRs are nice :-)

**Comment by Theoklitos** [comment]
They are :) I'll try and do a PR this weekend with what I have in mind.
