### ISSUE TITLE
Not a collaborator

### ISSUE THREAD

**Issue by psouza4** [kentcdodds/issue-template#39]
I'm not allowed to use your form to create a template because the button is disabled.  I updated the button properties to allow me to submit and got to the real issue: "You are not a collaborator on {user}/{repo}. You won't be able to save this template."

I am the owner of the repo and thus cannot be a collaborator (if I try to add myself as a collaborator, I get the error at Github "Repository owner cannot be a collaborator").

Do I really have to create a dummy Github account to assign collaborator permission in order to use your templating wizards?  I feel like we've missed something simple here (yes, I'm logged into issuetemplate.com with my github credentials and issue-template shows as an authorized application in my settings).

**Comment by kentcdodds** [comment]
That's odd... Nobody else has reported this at all. I don't know what to
say... Sorry :-/

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by psouza4** [comment]
Let me know if there's something I can do to test.

**Comment by kentcdodds** [comment]
I would try removing the app's permissions from your account and
reauthorizing.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by Stoyicker** [comment]
I'm experiencing the same as of now. Revoking app permissions did not work. @psouza4 did you ever get to work around this?

**Comment by psouza4** [comment]
Nope, I had already tried Kent's suggestion a number of times and was never able to get this working.  I abandoned my attempts and am currently not using any templates, unfortunately.

**Comment by kentcdodds** [comment]
Really sorry about that :-/ I don't have time to invest into figuring out what's going on. If you find anything out I'd be happy to accept PRs or update some auth configuration so this works for you.

**Comment by ant1b** [comment]
Same here: "Create" button stays disabled, deleting its "disabled" property allows click bringing up "not a collaborator" warning.

Suggest rolling back to last functional version while fix upcoming.

**Comment by ant1b** [comment]
It seems condition on line 19 of TemplateCtrl.js file is never fullfilled
Possibly due to the variable $scope.user.login always "undefined".


Tentative workaround (Using Firefox 40.0.2):

Of note: the exact labels of Firefox menus stated in what follows may not be 
absolutely accurate as they result from my hastened translation from those of 
my French Firefox interface.

Navigate to http://issuetemplate.com/#/new-template

Fill up at least mandatory fields of the web form. 
(this may be skipped at this point but will end up being 
more tedious to complete later-on in this workaround process 
due to the use of debugger stop-points set in the javascripts 
functions "watching" form entries).

Right click on "Create" button of the web form.
Select "inspect element" menu entry.
Should open Firefox dev tools
To the before last node of the following path:
```
<html class="ng-scope" ng-app="it">
 <body class="ng-scope" ng-controllers="MainCtrl">
  <div id="main container" class="center-block">
   <div class="ng-scope" ng-hide="loading" ng-view="">
    <div class="ng-scope">
     <div class="ng-scope" ng-if="user">
      <div class="" ng-hide="templateUrl">
       <form class="margin-top-medium ng-pristine ng-valid" role="form">
        <div class="pull-right">
         <button class="btn btn-primary ng-binding" ga="" ng-click="submitTemplate()" ng-disabled="!isCollaborator" type="submit" disabled="disabled">Create</button>
```
Double click on disabled="disabled" of the last node should allow editing of this node section field.
Delete the text content of this node section field. 
To be clear, content to be deleted reads as follows: disabled="disabled"
This should now allow the "Create" button of the web form to be responsive to mouse click.
However at this point, submitting the form would raise the "not a collaborator" warning message.


Access the Debugger tab of the Firefox dev tools.
In TemplateCtrl.js, add stop points at lines 18, 32 & 61.
These lines begin with:
18> function checkIfUserIsCollaborator() {
32> $scope.isCollaborator = false;
61> toastr.warning('You are not


Access the Debugger tab of the Firefox dev tools,
Press Ctrl+Shift+E
In the panel that slides in, set a new "spy expression" as follows: $scope.isCollaborator

Click the "Create" button of the web form.
Upon reaching the first stop-point,
Edit the value of $scope.isCollaborator displayed in the "spy expressions" section of the side panel,
From "false" to "true",
Then hit enter for validating, value "true" should now appear in red.
Click the "Play" button close to the top-left panel of the Debugger interface, 
Until the "not a collaborator" warning message is raised.
Click warning message away.
If Debugger "Play" status is "Pause" (i.e. not "Play"),
Then clicking the "Create" button of the web form allows the form to be created. Yipee!


Updating the form follows a very similar course of action with the button of the web form being called "Update" instead of "Create",
However, in order to access the editing page you may need to begin by accessing the page of your form first, 
Then add "/edit" at the end of the url and validate by pressing enter.

Of note: once the stop-points of the Debugger are activated, it is often necessary to press the "Play" button of the Debugger,
A few times until a stable "pause" position is reached in which the page is fully loaded and none of the script functions is running anymore.
Unless you do so, the elements of the web navigating Firefox window will not be responsive to mouse click.

**Comment by kentcdodds** [comment]
Should be fixed now!

**Comment by stoyicker** [comment]
Still not working - merged but not deployed?

**Comment by kentcdodds** [comment]
Indeed! Sorry, forgot that this is using the `gh-pages` branch rather than the `master` branch. Should be working now (or in a few seconds)...

**Comment by stoyicker** [comment]
Working now. Probably worth mentioning that when you enter both the user and repo name you get the pop up again (without pressing anything), but then everything works alright.
